### ISSUE TITLE
Running Result not found

### ISSUE THREAD

**Issue by YacratesWyh** [facebookresearch/Adversarial-Continual-Learning#1]
I am trying your code, while any of the tests are skipped. I am sure the data is correctly downloaded in /data.  Something goes wrong in main.py at      "   appr.train(t,dataset[t])  " .
How to produce the training part result? Are there some settings that I should change? 5 blank lines in the last part could be 5 running, I guess.
I've tried to redownload the git, I would be appreciated if you help me.
Thanks,
![20200420150136](https://user-images.githubusercontent.com/8447769/79728057-e6f0ff80-831f-11ea-9bff-373254ae85d0.jpg)

**Comment by SaynaEbrahimi** [comment]
Hi, the screen shot you have attached here does now show any error. Can you include the exact output you are getting?
