### ISSUE TITLE
No ability to load dataset from a non pickled files - noMnist

### ISSUE THREAD

**Issue by albertmel29** [facebookresearch/Adversarial-Continual-Learning#13]
Hi , thank you for making the code opensource. I am trying to load my own png image dataset to acl, however I encounter  some problems,

![image](https://user-images.githubusercontent.com/75031288/100247093-12129000-2f8e-11eb-98a1-f44b44df1aaa.png)

![image](https://user-images.githubusercontent.com/75031288/100246608-75e88900-2f8d-11eb-8fda-64eef95e3aac.png)
![image](https://user-images.githubusercontent.com/75031288/100246845-c52eb980-2f8d-11eb-874c-c2fa51fc765d.png)

**Comment by SaynaEbrahimi** [comment]
Hi, thank you for your interest in our work. Can you show your `Mydataset` class? It seems that you have not included classes in its argument.

**Comment by albertmel29** [comment]
Hi Sayna,

you was right I didnt include the classes in the arguments now its added whoever I am still having this issue:
TypeError: __init__() got an unexpected keyword argument 'memory_classes'

This is the code for the dataloader:


from __future__ import print_function
import sys
from typing import Dict, Any

if sys.version_info[0] == 2:
    import cPickle as pickle
else:
    import pickle

import torch.utils.data as data
import torch.utils.data
from .datasets_utils import *
from utils import *
from torchvision import transforms

class Mydataset(torch.utils.data.Dataset):
  def __init__(self, root, classes, task_num, num_samples_per_class, train, transform=None, target_transform=None, download=False):
    self.root = os.path.expanduser(root)
    self.transform = transform
    self.target_transform = target_transform
    self.train = train

    self.url = "http://localhost:8080/data/mydataset/mydataset.tar.gz"
    self.filename = 'mydataset.zip'
    fpath = os.path.join(root, self.filename)
    if not os.path.isfile(fpath):
        if not download:
            raise RuntimeError('Dataset not found. You can use download=True to download it')
        else:
            print('Downloading from ' + self.url)
            download_url(self.url, root, filename=self.filename)

    import zipfile
    zip_ref = zipfile.ZipFile(fpath, 'r')
    zip_ref.extractall(root)
    zip_ref.close()

    if self.train:
        fpath = os.path.join(root, 'Mydataset', 'Train')

    else:
        fpath = os.path.join(root, 'Mydataset', 'Test')

    X, Y = [], []
    folders = os.listdir(fpath)

    for folder in folders:
        folder_path = os.path.join(fpath, folder)
        for ims in os.listdir(folder_path):
            try:
                img_path = os.path.join(folder_path, ims)
                X.append(np.array(Image.open(img_path).convert('RGB')))
                Y.append(ord(folder) - 65)  # Folders are A-J so labels will be 0-9
            except:
                print("File {}/{} is broken".format(folder, ims))
    self.data = np.array(X)
    self.targets = Y

    self.num_classes = len(set(self.targets))

    if num_samples_per_class:
        x, y, tt, td = [], [], [], []
        for l in range(self.num_classes):
            indices_with_label_l = np.where(np.array(self.targets) == l)

            x_with_label_l = [self.data[item] for item in indices_with_label_l[0]]

     
            shuffled_indices = np.random.permutation(len(x_with_label_l))[:num_samples_per_class]
            x_with_label_l = [x_with_label_l[item] for item in shuffled_indices]
            y_with_label_l = [l] * len(shuffled_indices)

            x.append(x_with_label_l)
            y.append(y_with_label_l)

        self.data = np.array(sum(x, []))
        self.labels = sum(y, [])

    self.tt = [task_num for _ in range(len(self.data))]
    self.td = [task_num + 1 for _ in range(len(self.data))]


  def __getitem__(self, index):
    img, target, tt, td = self.data[index], self.targets[index], self.tt[index], self.td[index]

    img = Image.fromarray(img)  # .convert('RGB')
    img = self.transform(img)

    return img, target, tt, td


  def __len__(self):
    return len(self.data)


  def download(self):


    import errno
    root = os.path.expanduser(self.root)

    fpath = os.path.join(root, self.filename)

    try:
        os.makedirs(root)
    except OSError as e:
        if e.errno == errno.EEXIST:
            pass
        else:
            raise
    urllib.request.urlretrieve(self.url, fpath)

    import zipfile
    zip_ref = zipfile.ZipFile(fpath, 'r')
    zip_ref.extractall(root)
    zip_ref.close()




class DatasetGen(object):
    def __init__(self, args):
        super(DatasetGen, self).__init__()

        self.seed = args.seed
        self.batch_size=args.batch_size
        self.pc_valid=args.pc_valid
        self.root = args.data_dir
        self.latent_dim = args.latent_dim
        self.use_memory = args.use_memory

        self.num_tasks = args.ntasks
        self.num_classes = 25

        self.num_samples = args.samples

        self.inputsize = [1,244,244]
        #
        mean = [0.485, 0.456, 0.406]
        std = [0.229, 0.224, 0.225]

        #transformation compose
        self.transformation = transforms.Compose([transforms.ToTensor(), transforms.Normalize(mean, std)])

        #taskcla
        self.taskcla = [[t, int(self.num_classes / self.num_tasks)] for t in range(self.num_tasks)]

        self.indices = {}
        self.dataloaders = {}
        self.idx = {}

        self.num_workers = args.workers
        self.pin_memory = True

        np.random.seed(self.seed)
        self.task_ids = [[0,1], [2,3], [4,5], [6,7], [8,9], [10,11], [12,13], [14,15], [16,17], [18,19], [20,21], [22,23], [24,25]]
        self.train_set = {}
        self.test_set = {}

        #task memory
        #self.task_memory = [] or

        self.task_memory = {}
        for i in range(self.num_tasks):
            self.task_memory[i] = {}
            self.task_memory[i]['x'] = []
            self.task_memory[i]['y'] = []
            self.task_memory[i]['tt'] = []
            self.task_memory[i]['td'] = []

        #def get(task_id)
    def get(self, task_id):

            self.dataloaders[task_id] = {}
            sys.stdout.flush()

            if task_id == 0:
                memory_classes = None
                memory = None
            else:
                memory_classes = self.task_ids
                memory = self.task_memory
            print(self.task_ids[task_id])

            self.train_set[task_id] = Mydataset(root=self.root, classes=self.task_ids[task_id],
                                             memory_classes=None,  **_#here the error is occuring_** 
                                             memory=memory, task_num=task_id, train=True,
                                             download=False, transform=self.transformation)
            self.test_set[task_id] = Mydataset(root=self.root, classes=self.task_ids[task_id], memory_classes=None,
                                            memory=None, task_num=task_id, train=False,
                                            download=True, transform=self.transformation)

            split = int(np.floor(self.pc_valid * len(self.train_set[task_id])))
            train_split, valid_split = torch.utils.data.random_split(self.train_set[task_id],
                                                                     [len(self.train_set[task_id]) - split, split])

            train_loader = torch.utils.data.DataLoader(train_split, batch_size=self.batch_size,
                                                       num_workers=self.num_workers,
                                                       pin_memory=self.pin_memory, drop_last=True, shuffle=True)
            valid_loader = torch.utils.data.DataLoader(valid_split, batch_size=int(self.batch_size * self.pc_valid),
                                                       shuffle=True,
                                                       num_workers=self.num_workers, pin_memory=self.pin_memory,
                                                       drop_last=True)
            test_loader = torch.utils.data.DataLoader(self.test_set[task_id], batch_size=self.batch_size,
                                                      num_workers=self.num_workers,
                                                      pin_memory=self.pin_memory, drop_last=True, shuffle=True)

            self.dataloaders[task_id]['train'] = train_loader
            self.dataloaders[task_id]['valid'] = valid_loader
            self.dataloaders[task_id]['test'] = test_loader
            self.dataloaders[task_id]['name'] = 'Mydataset-{}-{}'.format(task_id, self.task_ids[task_id])

            print("Training set size:      {}  images of {}x{}".format(len(train_loader.dataset), self.inputsize[1],
                                                                       self.inputsize[1]))
            print("Validation set size:    {}  images of {}x{}".format(len(valid_loader.dataset), self.inputsize[1],
                                                                       self.inputsize[1]))
            print("Test set size:          {}  images of {}x{}".format(len(test_loader.dataset), self.inputsize[1],
                                                                       self.inputsize[1]))
            return self.dataloaders


    def update_memory(self, task_id):

        num_samples_per_class = self.num_samples // len(self.task_ids[task_id])
        mem_class_mapping = {i: i for i, c in enumerate(self.task_ids[task_id])}

        
        for i in range(len(self.task_ids[task_id])):
      
            data_loader = torch.utils.data.DataLoader(self.train_split[task_id], batch_size=1,
                                                      num_workers=self.num_workers,
                                                      pin_memory=self.pin_memory)
            
            randind = torch.randperm(len(data_loader.dataset))[:num_samples_per_class]

            
            for ind in randind:
                self.task_memory[task_id]['x'].append(data_loader.dataset[ind][0])
                self.task_memory[task_id]['y'].append(mem_class_mapping[i])
                self.task_memory[task_id]['tt'].append(data_loader.dataset[ind][2])
                self.task_memory[task_id]['td'].append(data_loader.dataset[ind][3])

        print('Memory updated by adding {} images'.format(len(self.task_memory[task_id]['x'])))



    def report_size(self,dataset_name,task_id):
        print("Dataset {} size: {} ".format(dataset_name, len(self.train_set[task_id])))

**Comment by SaynaEbrahimi** [comment]
You are getting this error for the same reason. Every time you instantiate `Mydataset` class, you should pass the same arguments that exist in the `__init__` function in `Mydataset`. You should be able to resolve this error by changing your `__init__()` function to 

```
class Mydataset(torch.utils.data.Dataset):
    def __init__(self, root, classes, task_num, memory_classes, memory, task_num, train, download, transform):
```

**Comment by albertmel29** [comment]
Thank you Sayna, I will test it and let you know, appreciated your assistance.

**Comment by SaynaEbrahimi** [comment]
No problem. Feel free to reopen this issue or open a new one if you had any questions.
