### ISSUE TITLE
A question about test

### ISSUE THREAD

**Issue by Nyn2019** [facebookresearch/Adversarial-Continual-Learning#14]
I have read your program, it is very well written. But there seems to be a problem with logic when testing data. 
Task module labels for data seem to be needed when testing the model. But we need to get the label of the data itself to get the task block label, right? But in actual application, it is impossible for us to obtain the label of the data to be detected, which means it is impossible to obtain the label of the task module. If so, what is the use of your proposed method?
我已经阅读了您的程序，它写得很好。 但是在测试数据时逻辑似乎存在问题。
测试模型时，似乎需要数据的任务模块标签。 但是我们需要获取数据本身的标签才能获取任务块标签，对吗？ 但是在实际应用中，我们不可能获得待检测数据的标签，这意味着不可能获得任务模块的标签。 如果是这样，您提出的方法有什么用呢？

**Comment by SaynaEbrahimi** [comment]
Hi, our method is not task-free at test time meaning that you should know the task id for inference. It has been explained in the paper more extensively.
