### ISSUE TITLE
Where do you use the replay buffer?

### ISSUE THREAD

**Issue by mipet23** [facebookresearch/Adversarial-Continual-Learning#15]
Hi, I have a question regarding the replay buffer. If I set use_memory = True in the config file, it has no effect. Where exactly do you use the replay buffer in the code?

**Comment by SaynaEbrahimi** [comment]
For using memory you should have `use_memory="yes"` and `samples=X` where `X` is the number of samples per class you want to keep. Memory is updated in the data loader generator for each dataset. For instance it is [here](https://github.com/facebookresearch/Adversarial-Continual-Learning/blob/a99dfadcc59a12d903af6e5366a025ca44b3af07/src/dataloaders/miniimagenet.py#L225) for miniImageNet.

**Comment by mipet23** [comment]
But where exactly do you use the replay buffer (for cifar) in the training process? I could not find anything about this. Would be very grateful for your help.
