### ISSUE TITLE
mini-ImageNet details used in the paper

### ISSUE THREAD

**Issue by pavanteja295** [facebookresearch/Adversarial-Continual-Learning#2]
Hello,
Thanks a lot for open sourcing the code. I want to reproduce the results using https://github.com/facebookresearch/Adversarial-Continual-Learning/ for miniImageNet for comparison. 

However, miniImagenet is divided into 64, 16, 20 classes as train, val, test splits in the original repository. Can you please let me know the exact indices of the images being used for the test and train for your model. I want to use the exact images for fair comparison. Each class has 600 images in miniImageNet dataset but which images amongst these are used for train and for test?

If possible it would be great if you can share me your data preparation code so that I could use it directly.

**Comment by SaynaEbrahimi** [comment]
Hi,
I just pushed the script I used to split the miniImagenet into training and test sets into the `data` directory. If you have the miniImagenet dataset pickled as described in the README.md file, you should be able to replicate the exact same dataset I used for training and testing.
