### ISSUE TITLE
Error while using Cifar 10 dataset

### ISSUE THREAD

**Issue by tito0202** [facebookresearch/Adversarial-Continual-Learning#8]
Hi Sayna,

I am testing Cifar10 dataset with the ACL code whatever samples value I provide in the config file I am getting this error once It reached saving the model for task 3 , its look like the generator is not generating any new samples ? your input is appreciated. 
    

Saving all models for task 3 ...
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

>>> Test on task  0 - CIFAR10-0-[26, 86, 2, 55, 75, 93, 16, 73, 54, 95]: loss=0.005, acc=100.0% <<<
>>> Test on task  1 - CIFAR10-1-[53, 92, 78, 13, 7, 30, 22, 24, 33, 8]: loss=0.353, acc= 87.6% <<<
>>> Test on task  2 - CIFAR10-2-[43, 62, 3, 71, 45, 48, 6, 99, 82, 76]: loss=0.715, acc= 50.0% <<<

Saved accuracies at ./checkpoints/1fe898adc337474abbf3eaacc1c71d8e/cifar10_10_tasks_seed_0.txt
**********************************************************************************************************************************************************************************************************************************************************
Files already downloaded and verified
Files already downloaded and verified
printing test_tt []
printing test_td []
Traceback (most recent call last):
  File "main.py", line 189, in <module>
    main(args)
  File "main.py", line 170, in main
    acc, bwt = run(args, n)
  File "main.py", line 98, in run
    dataset = dataloader.get(t)
  File "/home/tarek/ACL/Adversarial-Continual-Learning/src/dataloaders/cifar10.py", line 259, in get
    train_loader = torch.utils.data.DataLoader(train_split, batch_size=self.batch_size, num_workers=self.num_workers,
  File "/home/tarek/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 224, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "/home/tarek/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 95, in __init__
    raise ValueError("num_samples should be a positive integer "
**ValueError: num_samples should be a positive integer value, but got num_samples=0**

**Comment by SaynaEbrahimi** [comment]
Hi, 

Have you changed anything in the config file, eg batch size or pc_valid? if yes can you say what have you changed? It looks like you are using batch size of zero.

**Comment by tito0202** [comment]
Hi Sayna,

Thank you for your quick reply this is what I was changing, however even if I kept the commented values or the enabled one's still crashing please can you take a look and advise appreciated:
#num_runs: 5
num_runs: 1
experiment: "cifar10"
data_dir: "../data"
checkpoint: "./checkpoints/"
output: ""
tsne: "no"
diff: "yes"
lam: 1        #diff loss lambda
adv: 0.05     #adversarial loss regularizer
orth: 0.1     #diff loss regularizer

#ntasks:5
ntasks: 10
use_memory: "no"
#samples:2
samples: 5

e_lr: 0.01
e_wd: 0.01
s_step: 5

d_lr: 0.001
d_wd: 0.01
d_step: 1

lr_factor: 3
lr_min: 1.0e-06
lr_patience: 5
mom: 0.9

#nlayers:2
nlayers: 1
#units: 175
units: 50
head_units: 32
latent_dim: 128
#batch_size:16
batch_size: 10
#nepochs:20
nepochs: 5
pc_valid: 0.15

workers: 4
#device: "cuda:3"

**Comment by SaynaEbrahimi** [comment]
So your config file tells me that you are learning CIFAR10 in 10 tasks? One class at a time? It doesn't make much sense to me. This means every private module is now learning one class only. What is your loss function for that? ACL only works if there is at least 2 classes in each task.

**Comment by SaynaEbrahimi** [comment]
I am closing this issue since I did not hear back from you but feel free to reopen if your issue is not resolved.

**Comment by tito0202** [comment]
Sorry Sayna,  I was trying to understand further the config file before replying:

{ You have class numbers higher than 9 in there which shows you are still using cifar100}   CIFAR10-0-[26, 86, 2, 55, 75, 93, 16, 73, 54, 95] >> do u mean these one's? should be all time less than 9 cifar10 class number[0 to 9]?

one class at a time : is this where I can define the number of run ? 
I adjusted the configs to the below:
num_runs: 5
ntasks: 5
use_memory: "no"
samples: 5
nlayers: 2
units: 175
head_units: 32
latent_dim: 128
batch_size: 10
nepochs: 5
I also adjusted the cifar 10 model I had an issue in it I will run it again if the configs are good to go thank you in advance.

**Comment by tito0202** [comment]
hmm yes its looks like till now working I never reach this stage in the CIFAR 10  :)  accomplished first Run 0 Yay 
![image](https://user-images.githubusercontent.com/70996622/93560870-73364a00-f9c6-11ea-9cc3-2e6de44c4136.png)
